version: 2.1

commands:
  setup:
    description: Setup project for all further steps
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn --immutable

jobs:
  build:
    docker:
      - image: cimg/node:16.13
    steps:
      - setup
      - run:
          name: Lint
          command: yarn lint
          when: always
      - run:
          name: Test
          command: yarn test
          when: always
  